#
# migration YAML file
#
UP:
	create_table:
		rules:
			type:
				length: 4
			conditionCombination:
				default: all
				length: 3
			action:
				length: 20
			minimumPercent:
				default: 0.0000
				length: 6
			minimumCount:
				default: 0
				length: 5
			fkey: rollup
			no_dates: true
		rollups:
			rollupObjectiveSatisfied:
				type: string
				default: 'true'
				length: 5
				not_null: true
			rollupProgressCompletion:
				type: string
				default: 'true'
				length: 5
				not_null: true
			objectiveMeasureWeight:
				type: string
				default: '1.0000'
				length: 20
				not_null: true
			no_dates: true
		conditions:
			referencedObjective:
				length: 255
			measureThreshold:
				length: 7
			operator:
				default: 'noOp'
				length: 4
			codition: [string, 27, not_null]
			fkey: rule
			no_dates: true
DOWN:
	drop_tables: [rules,rollups,conditions]
